### ISSUE TITLE
(Regression) Build error: ‘gamepakWaitState’ was not declared in this scope

### ISSUE THREAD

**Issue by orbea** [libretro/vba-next#54]
OS: `Slackware64-current`
`gcc-5.3.0_multilib-x86_64-3alien`
```
src/gba.cpp: In function ‘void CPUUpdateRegister(uint32_t, uint16_t)’:
src/gba.cpp:12134:51: error: ‘gamepakWaitState’ was not declared in this scope
             memoryWait[0x08] = memoryWait[0x09] = gamepakWaitState[(value >> 2) & 3];
                                                   ^
src/gba.cpp:12135:57: error: ‘gamepakWaitState0’ was not declared in this scope
             memoryWaitSeq[0x08] = memoryWaitSeq[0x09] = gamepakWaitState0[(value >> 4) & 1];
                                                         ^
src/gba.cpp:12137:57: error: ‘gamepakWaitState1’ was not declared in this scope
             memoryWaitSeq[0x0a] = memoryWaitSeq[0x0b] = gamepakWaitState1[(value >> 7) & 1];
                                                         ^
src/gba.cpp:12139:57: error: ‘gamepakWaitState2’ was not declared in this scope
             memoryWaitSeq[0x0c] = memoryWaitSeq[0x0d] = gamepakWaitState2[(value >> 10) & 1];
                                                         ^
Makefile.libretro:359: recipe for target 'src/gba.o' failed
make: *** [src/gba.o] Error 1
```
Git bisect reveals commit  b08dbceda50f88460bfd46c9e9692966b3e2ff03 as the culprit.
```
$ git bisect bad
b08dbceda50f88460bfd46c9e9692966b3e2ff03 is the first bad commit
commit b08dbceda50f88460bfd46c9e9692966b3e2ff03
Author: NunaticAlumina <alternate.sec@gmail.com>
Date:   Thu Aug 18 17:09:11 2016 +0900

    Attempt to use extra threads on renderer. (a lot of gliches)

:040000 040000 f3c27f4033aadb7543027ccaef23124b39a74b83 544f15eaea0480219d02fe8bba4cb79e7fdf27d5 M src
```

**Comment by orbea** [comment]
This has been fixed. https://github.com/libretro/vba-next/pull/55/commits/04b548d7b0f2ba25bfdf9c622883049fa9de22cf
